---
output:
  html_document:
    highlight: null
    css: style.css
    self_contained: no
    keep_md: true
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(stringr)
date <- "05/13/2021"
quarter <- "Spring2021"
week_folder <- "05-13_Sebo"
title <- "Developing Robot Teammates that Enhance Social Dynamics in Human-Robot Teams"
speaker <- "Sarah Sebo"
department <- "Computer Science Department"
university <- "University of Chicago"
github_home <- "https://github.com/uchicago-computation-workshop"
#Update Weekly
issues_url <- "https://github.com/uchicago-computation-workshop/Spring2021/issues/7"
zoom_url <- "https://uchicago.zoom.us/meeting/register/tJMrdO2srzstGdcGpeGq1NsWKCTfJTSa4yk-"
#Papers
week_paper_ref0 <- "Strohkorb Sebo, S., Dong, L. L., Chang, N., & Scassellati, B. (2020, March). Strategies for the inclusion of human members within human-robot teams. In Proceedings of the 2020 ACM/IEEE International Conference on Human-Robot Interaction (pp. 309-317)."
week_paper_file0 <- "sebo_1.pdf"
week_paper_ref1 <- "Sebo, S., Dong, L. L., Chang, N., Lewkowicz, M., Schutzman, M., & Scassellati, B. (2020). The Influence of Robot Verbal Support on Human Team Members: Encouraging Outgroup Contributions and Suppressing Ingroup Supportive Behavior. Frontiers in Psychology, 11, 3584."
week_paper_file1 <- "sebo_2.pdf"

#No Need to Edit
week_repo <- paste0("https://github.com/uchicago-computation-workshop/",quarter,"/tree/master/",week_folder)

readings0 <- paste0("[", week_paper_ref0,"](https://github.com/uchicago-computation-workshop/",quarter,"/blob/master/", week_folder,"/",week_paper_file0,")")

readings1 <- paste0("[", week_paper_ref1,"](https://github.com/uchicago-computation-workshop/",quarter,"/blob/master/", week_folder,"/",week_paper_file1,")")

```



<br>

<h3 class=pfblock-header> The Computational Social Science Workshop Presents </h3>

<h1 class=pfblock-header3> `r speaker`</h1>
<h3 class=pfblock-header3> `r department` </h3>
<h3 class=pfblock-header3> `r university` </h3>

<br><br>



<p class=pfblock-header3>The <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> at the University of Chicago cordially invites you to attend this week's talk:</p>



<br>

<div class=pfblock-header3>
<h2 class=pfblock-header>
  <a href=`r week_repo`> `r title` </a>
</h2>

<br>
</div>



<p class=footertext2>

**Summary:**  This work explores the development of robots that improve the performance of human-robot teams by shaping team dynamics to promote inclusion and psychological safety. The first half of the talk will discuss two strategies to improve the inclusion of the human members of a human-robot team: 1) a specialized role to interact with the robot and 2) supportive utterances from the robot. The second half of the talk will focus on how human expression of backchannels (e.g., "mm hmm", "yeah") correlate with team social dynamics (inclusion, psychological safety) and how robot backchannels influence the human-robot team.

</p>

<br>

<h4 class=pfblock-header3> Thursday, `r date` </h4>
<h4 class=pfblock-header3> 11:20am-12:40pm </h4>

<br><br>

<p class=footertext2>

**Sarah Sebo** is an Assistant Professor in the Computer Science Department at the University of Chicago. Her research explores social dynamics in human-robot interactions, where a robot's social behaviors lead to positive outcomes for people. Dr. Sebo completed her Ph.D. at Yale University where she worked with Dr. Brian Scassellati in the Social Robotics Lab and her B.S. in Electrical and Computer Engineering from Franklin W. Olin College of Engineering. .

</p>

<br>

**Registration**: The presentation will be held virtually on Zoom. For security purposes, please register through this [link](`r zoom_url`) to request access. Only accounts affiliated with the University of Chicago will be granted access.

<br>

This week's recommended reading:

- `r readings0`

- `r readings1`

<br>

<br><br>

---

<p class=footertext> The 2020-2021 <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> meets each Thursday from 11:20 a.m. to 12:40 p.m. All interested faculty and graduate students are welcome.</p>



<p class=footertext>Students in the Masters of Computational Social Science program are expected to attend and join the discussion by posting a comment on the <a href=`r issues_url`>issues page</a> of the <a href=`r week_repo`>workshop's public repository on GitHub.</a></p>

