---
output:
  html_document:
    highlight: null
    css: style.css
    self_contained: no
    keep_md: true
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(stringr)
date <- "04/01/2021"
quarter <- "Spring2021"
week_folder <- "04-01_Stoica"
title <- "Seeding Network Influence in Biased Networks and the Benefits of Diversity"
speaker <- "Ana-Andreea Stoica"
department <- "Computer Science Department"
university <- "Columbia University"
github_home <- "https://github.com/uchicago-computation-workshop"
#Update Weekly
issues_url <- "https://github.com/uchicago-computation-workshop/Winter2021/issues/1"
zoom_url <- "https://uchicago.zoom.us/meeting/register/tJUodu6urD4uGtGyWjio-w5DPZ-ElCri9nzt"
#Papers
week_paper_ref0 <- "Stoica, A.A., Han, J.X., Chaintreau, A. (2020). Seeding Network Influence in Biased Networks and the Benefits of Diversity. Proceedings of The Web Conference 2020, (pp. 2089-2098)."
week_paper_file0 <- "socialinfluence.pdf"
week_paper_ref1 <- "Stoica, A.A., Riederer, C., Chaintreau, A. (2018). Algorithmic Glass Ceiling in Social Networks: The effects of social recommendations on network diversity. Proceedings of the 2018 World Wide Web Conference (pp. 923-932)."
week_paper_file1 <- "recommendationglassceiling.pdf"


#No Need to Edit
week_repo <- paste0("https://github.com/uchicago-computation-workshop/",quarter,"/tree/master/",week_folder)

readings0 <- paste0("[", week_paper_ref0,"](https://github.com/uchicago-computation-workshop/",quarter,"/blob/master/", week_folder,"/",week_paper_file0,")")

readings1 <- paste0("[", week_paper_ref1,"](https://github.com/uchicago-computation-workshop/",quarter,"/blob/master/", week_folder,"/",week_paper_file1,")")


```



<br>

<h3 class=pfblock-header> The Computational Social Science Workshop Presents </h3>

<h1 class=pfblock-header3> `r speaker`</h1>
<h3 class=pfblock-header3> `r department` </h3>
<h3 class=pfblock-header3> `r university` </h3>

<br><br>



<p class=pfblock-header3>The <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> at the University of Chicago cordially invites you to attend this week's talk:</p>



<br>

<div class=pfblock-header3>
<h2 class=pfblock-header>
  <a href=`r week_repo`> `r title` </a>
</h2>

<br>
</div>



<p class=footertext2>

**Summary:** The problem of social influence maximization is widely applicable in designing viral campaigns, news dissemination, or medical aid. State-of-the-art algorithms often select “early adopters” that are most central in a network unfortunately mirroring or exacerbating historical biases and leaving under-represented communities out of the loop. Through a theoretical model of biased networks, we characterize the intricate relationship between diversity and efficiency, which sometimes may be at odds but may also reinforce each other. Most importantly, we find a mathematically proven analytical condition
under which more equitable choices of early adopters lead simultaneously to fairer outcomes and larger outreach. Analysis of data on the DBLP network confirms that our condition is often met in real networks. We design and test a set of algorithms leveraging the network structure to optimize the diffusion of a message while avoiding to create disparate impact among participants based on their demographics, such as gender or race.

</p>

<br>

<h4 class=pfblock-header3> Thursday, `r date` </h4>
<h4 class=pfblock-header3> 11:20am-12:40pm </h4>

<br><br>

<p class=footertext2>

**Ana-Andreea Stoica** is a Ph.D. candidate at Columbia University. Her work focuses on mathematical models, data analysis, and inequality in social networks. From recommendation algorithms to the way information spreads in networks, Ana is particularly interested in studying the effect of algorithms on people's sense of privacy, community, and access to information and opportunities. She strives to integrate tools from mathematical models—from graph theory to opinion dynamics—with sociology to gain a deeper understanding of the ethics and implications of technology in our everyday lives. Ana grew up in Bucharest, Romania, and moved to the US for college, where she graduated from Princeton in 2016 with a bachelor's degree in Mathematics. Since 2019, she has been co-organizing the Mechanism Design for Social Good initiative.
</p>

<br>

<p class=footertext2>
**Registration**: The presentation will be held virtually on Zoom. For security purposes, please register through this [link](`r zoom_url`) to request access. Only accounts affiliated with the University of Chicago will be granted access.
</p>

<br>
This week's suggested readings:

- `r readings0`
- `r readings1`

<br>

<br><br>

---

<p class=footertext> The 2020-2021 <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> meets each Thursday from 11:20 a.m. to 12:40 p.m.. All interested faculty and graduate students are welcome.</p>



<p class=footertext>Students in the Masters of Computational Social Science program are expected to attend and join the discussion by posting a comment on the <a href=`r issues_url`>issues page</a> of the <a href=`r week_repo`>workshop's public repository on GitHub.</a></p>
