---
output:
  html_document:
    highlight: null
    css: style.css
    self_contained: no
    keep_md: true
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(stringr)
date <- "05/27/2021"
quarter <- "Spring2021"
week_folder <- "05-27_Pope"
title <- "The Many Markets Impacted by Left-Digit Bias"
speaker <- "Devin Pope"
department <- "Booth School of Business"
university <- "University of Chicago"
github_home <- "https://github.com/uchicago-computation-workshop"
#Update Weekly
issues_url <- "https://github.com/uchicago-computation-workshop/Spring2021/issues/9"
zoom_url <- "https://uchicago.zoom.us/meeting/register/tJYvceGhqz4tEtSZpUqhQMWDWN5Z7pDkL-qH"
#Papers
week_paper_ref0 <- "Lacetera, N., Pope, D. G., & Sydnor, J. R. (2012). Heuristic thinking and limited attention in the car market. American Economic Review, 102(5), 2206-36."
week_paper_file0 <- "pope_1.pdf"

#No Need to Edit
week_repo <- paste0("https://github.com/uchicago-computation-workshop/",quarter,"/tree/master/",week_folder)

readings0 <- paste0("[", week_paper_ref0,"](https://github.com/uchicago-computation-workshop/",quarter,"/blob/master/", week_folder,"/",week_paper_file0,")")


```



<br>

<h3 class=pfblock-header> The Computational Social Science Workshop Presents </h3>

<h1 class=pfblock-header3> `r speaker`</h1>
<h3 class=pfblock-header3> `r department` </h3>
<h3 class=pfblock-header3> `r university` </h3>

<br><br>



<p class=pfblock-header3>The <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> at the University of Chicago cordially invites you to attend this week's talk:</p>



<br>

<div class=pfblock-header3>
<h2 class=pfblock-header>
  <a href=`r week_repo`> `r title` </a>
</h2>

<br>
</div>



<p class=footertext2>

**Summary:** In this talk, I will discuss older work looking at left-digit bias in the car market followed by ongoing work looking at left-digit bias with Lyft. We will explore why this bias is so prevalent and why many large companies fail to incorporate this bias into their pricing strategy.

</p>

<br>

<h4 class=pfblock-header3> Thursday, `r date` </h4>
<h4 class=pfblock-header3> 11:20am-12:40pm </h4>

<br><br>

<p class=footertext2>

**Devin Pope** studies a variety of topics at the intersection of economics and psychology. He has published work in top economics outlets such as the American Economic Review, Quarterly Journal of Economics, Journal of Political Economy, and Review of Economic Studies. He has also published in psychology and multidisciplinary outlets such as Management Science and Psychological Science. Using primarily observational data, Pope studies how psychological biases play out in field settings and economic markets. Examples include left-digit bias and projection bias in car markets and time inconsistency in housing markets. Prior to joining the Chicago Booth faculty in 2010, Pope was on the faculty at the Wharton School at the University of Pennsylvania. He earned a PhD in economics from UC Berkeley in 2007 and a BA in economics from Brigham Young University in 2002.

</p>

<br>

**Registration**: The presentation will be held virtually on Zoom. For security purposes, please register through this [link](`r zoom_url`) to request access. Only accounts affiliated with the University of Chicago will be granted access.

<br>

This week's recommended reading:

- `r readings0`


<br>

<br><br>

---

<p class=footertext> The 2020-2021 <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> meets each Thursday from 11:20 a.m. to 12:40 p.m. All interested faculty and graduate students are welcome.</p>



<p class=footertext>Students in the Masters of Computational Social Science program are expected to attend and join the discussion by posting a comment on the <a href=`r issues_url`>issues page</a> of the <a href=`r week_repo`>workshop's public repository on GitHub.</a></p>

