---
output:
  html_document:
    highlight: null
    css: style.css
    self_contained: no
    keep_md: true
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(stringr)
date <- "05/20/2021"
quarter <- "Spring2021"
week_folder <- "05-20_Ettinger"
title <- "'Understanding' and prediction: Controlled examinations of meaning sensitivity in pre-trained NLP models"
speaker <- "Allyson Ettinger"
department <- "Linguistics Department"
university <- "University of Chicago"
github_home <- "https://github.com/uchicago-computation-workshop"
#Update Weekly
issues_url <- "https://github.com/uchicago-computation-workshop/Spring2021/issues/8"
zoom_url <- "https://uchicago.zoom.us/meeting/register/tJAtcu6orDkjGtWINbyRzuaU79w3KU-tDIm3"
#Papers
week_paper_ref0 <- "Ettinger, A. (2020). What BERT is not: Lessons from a new suite of psycholinguistic diagnostics for language models. Transactions of the Association for Computational Linguistics, 8, 34-48."
week_paper_file0 <- "ettinger_1.pdf"
week_paper_ref1 <- "Yu, L., & Ettinger, A. (2020). Assessing Phrasal Representation and Composition in Transformers. arXiv preprint arXiv:2010.03763."
week_paper_file1 <- "ettinger_2.pdf"
week_paper_ref2 <- "Ettinger, A., Elgohary, A., Phillips, C., Resnik, P. (2018). Assessing Composition in Sentence Vector Representations. Proceedings of the 27th International Conference on Computational Linguistics."
week_paper_file2 <- "ettinger_3.pdf"

#No Need to Edit
week_repo <- paste0("https://github.com/uchicago-computation-workshop/",quarter,"/tree/master/",week_folder)

readings0 <- paste0("[", week_paper_ref0,"](https://github.com/uchicago-computation-workshop/",quarter,"/blob/master/", week_folder,"/",week_paper_file0,")")

readings1 <- paste0("[", week_paper_ref1,"](https://github.com/uchicago-computation-workshop/",quarter,"/blob/master/", week_folder,"/",week_paper_file1,")")

readings2 <- paste0("[", week_paper_ref2,"](https://github.com/uchicago-computation-workshop/",quarter,"/blob/master/", week_folder,"/",week_paper_file2,")")

```



<br>

<h3 class=pfblock-header> The Computational Social Science Workshop Presents </h3>

<h1 class=pfblock-header3> `r speaker`</h1>
<h3 class=pfblock-header3> `r department` </h3>
<h3 class=pfblock-header3> `r university` </h3>

<br><br>



<p class=pfblock-header3>The <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> at the University of Chicago cordially invites you to attend this week's talk:</p>



<br>

<div class=pfblock-header3>
<h2 class=pfblock-header>
  <a href=`r week_repo`> `r title` </a>
</h2>

<br>
</div>



<p class=footertext2>

**Summary:** In recent years, NLP has made what appears to be incredible progress, with performance even surpassing human performance on some benchmarks. How should we interpret these advances? Have these models achieved language "understanding"? Operating on the premise that "understanding" will necessarily involve the capacity to extract and deploy meaning information from linguistic input, in this talk I will discuss projects leveraging targeted tests to examine NLP models' ability to capture linguistic meaning in a systematic fashion. I will first discuss work probing model representations for signs of systematic, humanlike composition of complex meaning at the phrase and sentence level. I'll then explore models' ability to deploy meaning information during word prediction, applying tests designed by psycholinguists, and comparing model predictions against human predictive responses of varying linguistic sensitivity. In all cases, these investigations apply tests that prioritize control of unwanted cues, so as to target the desired meaning capabilities with greater precision. The results of these studies suggest that although models show a good deal of sensitivity to word-level information, and to a number of semantic and syntactic distinctions, they show little sign of capturing higher-level compositional meaning, or of capturing logical impacts of meaning components like negation. I will discuss potential implications of these findings with respect to the goals of achieving "understanding" with the currently dominant pre-training paradigms in NLP.

</p>

<br>

<h4 class=pfblock-header3> Thursday, `r date` </h4>
<h4 class=pfblock-header3> 11:20am-12:40pm </h4>

<br><br>

<p class=footertext2>

**Allyson Ettinger** is an Assistant Professor in the University of Chicago Department of Linguistics. Her interdisciplinary work combines methods and insights from cognitive science, linguistics, and computer science to examine meaning extraction and predictive processes executed during language processing in artificial intelligence systems and in humans. She received her PhD in Linguistics from the University of Maryland, and spent a year as research faculty at the Toyota Technological Institute at Chicago (TTIC) before beginning her appointment at the University of Chicago. She holds an additional courtesy appointment at TTIC.

</p>

<br>

**Registration**: The presentation will be held virtually on Zoom. For security purposes, please register through this [link](`r zoom_url`) to request access. Only accounts affiliated with the University of Chicago will be granted access.

<br>

This week's required reading::

- `r readings0`

This week's additional suggested reading (in order of priority):

- `r readings1`

- `r readings2`

<br>

<br><br>

---

<p class=footertext> The 2020-2021 <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> meets each Thursday from 11:20 a.m. to 12:40 p.m. All interested faculty and graduate students are welcome.</p>



<p class=footertext>Students in the Masters of Computational Social Science program are expected to attend and join the discussion by posting a comment on the <a href=`r issues_url`>issues page</a> of the <a href=`r week_repo`>workshop's public repository on GitHub.</a></p>

