---
output:
  html_document:
    highlight: null
    css: style.css
    self_contained: no
    keep_md: true
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(stringr)
date <- "05/06/2021"
quarter <- "Spring2021"
week_folder <- "05-06_Kosinski"
title <- "Psychological Profiling in the Digital Environment: Risks and Opportunities"
speaker <- "Michal Kosinski"
department <- "Stanford Graduate School of Business"
university <- "Stanford University"
github_home <- "https://github.com/uchicago-computation-workshop"
#Update Weekly
issues_url <- "https://github.com/uchicago-computation-workshop/Spring2021/issues/6"
zoom_url <- "https://uchicago.zoom.us/meeting/register/tJwod-yqpzktGtFW7QPdJe_RluIlNTCWoJ6b"
#Papers
week_paper_ref0 <- "Kosinski, M. (2021). Facial recognition technology can expose political orientation from naturalistic facial images. Scientific Reports, 11(1), 1-7."
week_paper_file0 <- "kosinski_1.pdf"
week_paper_ref1 <- "Youyou, W., Kosinski, M., & Stillwell, D. (2015). Computer-based personality judgments are more accurate than those made by humans. Proceedings of the National Academy of Sciences, 112(4), 1036-1040."
week_paper_file1 <- "kosinski_2.pdf"

#No Need to Edit
week_repo <- paste0("https://github.com/uchicago-computation-workshop/",quarter,"/tree/master/",week_folder)

readings0 <- paste0("[", week_paper_ref0,"](https://github.com/uchicago-computation-workshop/",quarter,"/blob/master/", week_folder,"/",week_paper_file0,")")

readings1 <- paste0("[", week_paper_ref1,"](https://github.com/uchicago-computation-workshop/",quarter,"/blob/master/", week_folder,"/",week_paper_file1,")")

```



<br>

<h3 class=pfblock-header> The Computational Social Science Workshop Presents </h3>

<h1 class=pfblock-header3> `r speaker`</h1>
<h3 class=pfblock-header3> `r department` </h3>
<h3 class=pfblock-header3> `r university` </h3>

<br><br>



<p class=pfblock-header3>The <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> at the University of Chicago cordially invites you to attend this week's talk:</p>



<br>

<div class=pfblock-header3>
<h2 class=pfblock-header>
  <a href=`r week_repo`> `r title` </a>
</h2>

<br>
</div>



<p class=footertext2>

**Summary:** A growing proportion of human activities―such as social interactions, entertainment, shopping, and gathering information―are now mediated by digital devices and services. Such digitally mediated activities can be easily recorded, offering an unprecedented opportunity to study and assess psychological traits using actual (rather than self-reported) behavior. Our research shows that digital records of behavior―such as facial images, samples of text, Tweets, Facebook Likes, or web-browsing logs―can be used to accurately measure a wide range of psychological traits. Such predictions do not require participants' active involvement; can be easily and inexpensively applied to large populations; and are relatively immune to misrepresentation. Consequently, the predictability of psychological traits offers a promise to improve research and practice in fields ranging from psychology, sociology, and education to management and marketing. However, if applied unethically, the same models pose unprecedented risks to the privacy and well-being of entire societies. 

</p>

<br>

<h4 class=pfblock-header3> Thursday, `r date` </h4>
<h4 class=pfblock-header3> 11:20am-12:40pm </h4>

<br><br>

<p class=footertext2>

**Michal Kosinski** is an Associate Professor in Organizational Behavior at Stanford University Graduate School of Business. He studies humans in a digital environment using cutting-edge computational methods, AI and Big Data. Michal published over 70 papers in leading journals including Proceedings of the National Academy of Sciences, Machine Learning, Psychological Science, and Journal of Personality and Social Psychology, that have been cited over 12,000 times and earned him a 2015 Rising Star award from the Association of Psychological Science. His research inspired a cover of The Economist, a 2014 theatre play “Privacy,” multiple TED talks, a video game, and was discussed in thousands of books, press articles, podcasts, and documentaries. Also, he was the first to warn against the privacy risks later employed by Cambridge Analytica. Michal received his PhD in Psychology from the University of Cambridge (UK) in 2014. Prior to his current appointment, he was a Postdoctoral Scholar at Stanford's Computer Science Department and a researcher at Microsoft Research.

</p>

<br>

**Registration**: The presentation will be held virtually on Zoom. For security purposes, please register through this [link](`r zoom_url`) to request access. Only accounts affiliated with the University of Chicago will be granted access.

<br>

This week's recommended reading:

- `r readings0`

- `r readings1`

<br>

<br><br>

---

<p class=footertext> The 2020-2021 <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> meets each Thursday from 11:20 a.m. to 12:40 p.m. All interested faculty and graduate students are welcome.</p>



<p class=footertext>Students in the Masters of Computational Social Science program are expected to attend and join the discussion by posting a comment on the <a href=`r issues_url`>issues page</a> of the <a href=`r week_repo`>workshop's public repository on GitHub.</a></p>

