---
output:
  html_document:
    highlight: null
    css: style.css
    self_contained: no
    keep_md: true
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(stringr)
date <- "04/29/2021"
quarter <- "Spring2021"
week_folder <- "04-29_Rahwan"
title <- "How to Trust a Machine?"
speaker <- "Iyad Rahwan"
department <- "Center for Humans and Machines"
university <- "Max Planck Institute for Human Development "
github_home <- "https://github.com/uchicago-computation-workshop"
#Update Weekly
issues_url <- "https://github.com/uchicago-computation-workshop/Spring2021/issues/5"
zoom_url <- "https://uchicago.zoom.us/meeting/register/tJUlcuGurzgoHN2J5RJuOaZjJs5Zp27ifRur"
#Papers
week_paper_ref0 <- "E. Awad, S. Dsouza, R. Kim, J. Schulz, J. Henrich, A. Shariff, J.-F. Bonnefon, I. Rahwan (2018). The Moral Machine experiment. Nature. 562 (7729)."
week_paper_file0 <- "rahwan_reading1.pdf"
week_paper_ref1 <- "E. Awad, S. Dsouza, J.-F. Bonnefon, A. Shariff, I. Rahwan (2020). Crowdsourcing Moral Machines. Communications of the ACM, March 2020, Vol. 63 No. 3, Pages 48-55."
week_paper_file1 <- "rahwan_reading2.pdf"
week_paper_ref2 <- "I. Rahwan, et al (2019). Machine Behaviour. Nature. 68, pages 477–486."
week_paper_file2 <- "rahwan_reading3.pdf"

#No Need to Edit
week_repo <- paste0("https://github.com/uchicago-computation-workshop/",quarter,"/tree/master/",week_folder)

readings0 <- paste0("[", week_paper_ref0,"](https://github.com/uchicago-computation-workshop/",quarter,"/blob/master/", week_folder,"/",week_paper_file0,")")

readings1 <- paste0("[", week_paper_ref1,"](https://github.com/uchicago-computation-workshop/",quarter,"/blob/master/", week_folder,"/",week_paper_file1,")")

readings2 <- paste0("[", week_paper_ref2,"](https://github.com/uchicago-computation-workshop/",quarter,"/blob/master/", week_folder,"/",week_paper_file2,")")

```



<br>

<h3 class=pfblock-header> The Computational Social Science Workshop Presents </h3>

<h1 class=pfblock-header3> `r speaker`</h1>
<h3 class=pfblock-header3> `r department` </h3>
<h3 class=pfblock-header3> `r university` </h3>

<br><br>



<p class=pfblock-header3>The <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> at the University of Chicago cordially invites you to attend this week's talk:</p>



<br>

<div class=pfblock-header3>
<h2 class=pfblock-header>
  <a href=`r week_repo`> `r title` </a>
</h2>

<br>
</div>



<p class=footertext2>

**Summary:** Machine intelligence plays a growing role in our lives. How do we ensure that these machines will be trustworthy? This talk explores various psychological, social, cultural and political factors that shape our trust in machines. It will also propose an interdisciplinary agenda for understanding and improving our human-machine ecology.  

</p>

<br>

<h4 class=pfblock-header3> Thursday, `r date` </h4>
<h4 class=pfblock-header3> 11:20am-12:40pm </h4>

<br><br>

<p class=footertext2>

**Iyad Rahwan** is a director of the Max Planck Institute for Human Development in Berlin,  where he founded and directs the Center for Humans & Machines. He is also an honorary professor of Electrical Engineering and Computer Science at the Technical University of Berlin. Until June 2020, he was an Associate Professor of Media Arts & Sciences at the Massachusetts Institute of Technology (MIT). A native of Aleppo, Syria, Rahwan holds a PhD from the University of Melbourne, Australia.

</p>

<br>

**Registration**: The presentation will be held virtually on Zoom. For security purposes, please register through this [link](`r zoom_url`) to request access. Only accounts affiliated with the University of Chicago will be granted access.

<br>

This week's recommended reading:

- `r readings0`

- `r readings1`

- `r readings2`

<br>

<br><br>

---

<p class=footertext> The 2020-2021 <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> meets each Thursday from 11:20 a.m. to 12:40 p.m. All interested faculty and graduate students are welcome.</p>



<p class=footertext>Students in the Masters of Computational Social Science program are expected to attend and join the discussion by posting a comment on the <a href=`r issues_url`>issues page</a> of the <a href=`r week_repo`>workshop's public repository on GitHub.</a></p>

