---
output:
  html_document:
    highlight: null
    css: style.css
    self_contained: no
    keep_md: true
---

```{r, echo=FALSE, warning=FALSE, message=FALSE}
library(stringr)
date <- "04/08/2021"
quarter <- "Spring2021"
week_folder <- "04-08_Bakshy"
title <- "Efficient Experimental Design with Adaptive Experimentation"
speaker <- "Eytan Bakshy"
department <- "Facebook Core Data Science Team"
university <- "Facebook"
github_home <- "https://github.com/uchicago-computation-workshop"
#Update Weekly
issues_url <- "https://github.com/uchicago-computation-workshop/Spring2021/issues/1"
zoom_url <- "https://uchicago.zoom.us/meeting/register/tJErfu6vqjMpE9xmQAuBstken9es1UOfeBzh"
#Papers
week_paper_ref0 <- "Letham, B., Feng, Q., Daulton, S., Bakshy, E. (2021). Real-World Bayesian Optimization with A/B Tests."
week_paper_file0 <- "bayesopt_for_ab_testing_review.pdf"
week_paper_ref1 <- "Letham, B., Karrer, B., Ottoni, G., Bakshy, E. (2019). Constrained Bayesian Optimization with Noisy Experiments. Bayesian Analysis, 14(2), (pp. 495-519)."
week_paper_file1 <- "18_BA1110.pdf"
week_paper_ref2 <- "Bakshy, E., Dworkin, L., Karrer, B., Kashin, K., Letham, B., Murthy, A., Singh, S. (2018). AE: A domain-agnostic platform for adaptive experimentation. In 'Workshop on System for ML.'"
week_paper_file2 <- "ae_workshop_2018.pdf"


#No Need to Edit
week_repo <- paste0("https://github.com/uchicago-computation-workshop/",quarter,"/tree/master/",week_folder)

readings0 <- paste0("[", week_paper_ref0,"](https://github.com/uchicago-computation-workshop/",quarter,"/blob/master/", week_folder,"/",week_paper_file0,")")

readings1 <- paste0("[", week_paper_ref1,"](https://github.com/uchicago-computation-workshop/",quarter,"/blob/master/", week_folder,"/",week_paper_file1,")")

readings2 <- paste0("[", week_paper_ref2,"](https://github.com/uchicago-computation-workshop/",quarter,"/blob/master/", week_folder,"/",week_paper_file2,")")


```



<br>

<h3 class=pfblock-header> The Computational Social Science Workshop Presents </h3>

<h1 class=pfblock-header3> `r speaker`</h1>
<h3 class=pfblock-header3> `r department` </h3>
<h3 class=pfblock-header3> `r university` </h3>

<br><br>



<p class=pfblock-header3>The <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> at the University of Chicago cordially invites you to attend this week's talk:</p>



<br>

<div class=pfblock-header3>
<h2 class=pfblock-header>
  <a href=`r week_repo`> `r title` </a>
</h2>

<br>
</div>



<p class=footertext2>

**Summary:** Most randomized experiments consider a limited number of treatments in an effort to obtain statistical power with respect to some particular hypothesis.  However, in many problem domains, there may be dozens or even an infinite number of possible treatments that a researcher or practitioner may wish to consider.  Such problems naturally arise in optimization problems, such as increasing recruitment or participation into a program, or understanding the effects of one or more continuous treatment (such as the intensity of a stimuli).  Drawing on applied work at Facebook, I will discuss approaches to efficient experimentation techniques including multi-armed bandit optimization, Bayesian optimization, and personalized policy search.

</p>

<br>

<h4 class=pfblock-header3> Thursday, `r date` </h4>
<h4 class=pfblock-header3> 11:20am-12:40pm </h4>

<br><br>

<p class=footertext2>

**Eytan Bakshy** is the principal scientist and director on the Facebook Core Data Science Team, where he leads the Adaptive Experimentation group. Eytan is particularly interested in developing practical and robust methods for sequential experimentation and reinforcement learning for real-world applications. Much of Eytan's work has beeen motivated by the use of randomized experiments for understanding social behavior, including influence and information diffusion in networks.
</p>

<br>

<p class=footertext2>
**Registration**: The presentation will be held virtually on Zoom. For security purposes, please register through this [link](`r zoom_url`) to request access. Only accounts affiliated with the University of Chicago will be granted access.
</p>

<br>
This week's recommended reading:

- `r readings0`

Additional suggestions for optional reading:

- `r readings1`
- `r readings2`

<br>

<br><br>

---

<p class=footertext> The 2020-2021 <a href="https://macss.uchicago.edu/content/computation-workshop"> Computational Social Science Workshop </a> meets each Thursday from 11:20 a.m. to 12:40 p.m. All interested faculty and graduate students are welcome.</p>



<p class=footertext>Students in the Masters of Computational Social Science program are expected to attend and join the discussion by posting a comment on the <a href=`r issues_url`>issues page</a> of the <a href=`r week_repo`>workshop's public repository on GitHub.</a></p>

